# Generated by Django 5.1.6 on 2025-04-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ekyc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="pin",
        ),
    ]
