# Generated by Django 5.1.5 on 2025-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekyc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
