name: EKYC Project Test

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root.123
          MYSQL_DATABASE: ekyc
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify MySQL connection
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: ekyc_project.settings
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: ekyc
          DB_USER: root
          DB_PASSWORD: root.123
        run: python manage.py migrate

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: ekyc_project.settings
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: ekyc
          DB_USER: root
          DB_PASSWORD: root.123
        run: python manage.py test

