name: EKYC Project Test

on:
  push:
    branches:
      - 'dev'

  pull_request:
    branches:
      - 'main'


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run migrations
        run: python manage.py migrate

      - name: run tests
        run: python manage.py test
  
